# Generated by Django 4.2.2 on 2023-06-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='Bidder',
            new_name='bidder',
        ),
    ]
